php:
  build: ./docker
  links:
      - db
  volumes:
    - .:/var/www/docker-symfony
    - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1
    PHP_IDE_CONFIG: serverName=docker-symfony
nginx:
  image: nginx:1.9.10
  links:
    - php
  volumes_from:
    - php
  volumes:
    - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
db:
  image: postgres:9.5
  ports:
    - "5432:5432"
  volumes:
    - ./var/logs/postgres:/var/log/postgresql
  environment:
    POSTGRES_USER: pg_user
    POSTGRES_PASSWORD: KzkFbtoxHXxizqZoSqzg
    POSTGRES_DB: cv