parameters:
    app.parser.root: datas
    app.schema.dataset.path: "src/AppBundle/Schema/dataset"

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@router"
        tags:
            - { name: knp_menu.menu_builder, method: createHomeMenu, alias: home }

    # Parser
    app.parser.json:
        class: AppBundle\Parser\JsonParser
        arguments:
            - "%app.parser.root%"

    # Schema
    app.schema:
        class: AppBundle\Schema\Schema
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.parser.json"
            - "%app.schema.dataset.path%"

    # Manager
    app.manager:
        class: AppBundle\Manager\CVManager
        arguments:
            - "@doctrine.orm.entity_manager"