#!/bin/bash

# npm root install
apt-get install -y wget xz-utils
wget https://nodejs.org/dist/v4.4.3/node-v4.4.3-linux-x64.tar.xz
tar xvf node-v4.4.3-linux-x64.tar.xz
cp -rf node-v4.4.3-linux-x64 /opt/node
rm -rf node-v4.4.3-linux-x64*
ln -s /opt/node/bin/node /usr/local/bin/node
ln -s /opt/node/bin/npm /usr/local/bin/npm
npm install -g npm
